version: "3.8"

services:
  bot:
    build: .
    environment:
      - HF_ENDPOINT_URL=${HF_ENDPOINT_URL}
      - HF_API_TOKEN=${HF_API_TOKEN}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./ems:/app/ems
    restart: unless-stopped
